api_key: ""
api_secret: ""
api_passphrase: ""
ws_url: "ws://127.0.0.1:8084/"
rest_url: ""
symbol: "BTCUSD.PERP"
index_symbol: ".BTCUSD"
check_position_limits: false
trading_params:
  order_size_decay: 1.5
  min_spread: 0.01
  maintain_spread: true
  price_decay: 0.001
  relist_tollerance: 0.001
  start_order_size: 50
  is_random_order_size: false
  order_step_size: 10
  n_levels: 3
  max_long_pos_btc: 1
  max_short_pos_btc: 1